version: "3.9"

services:
  catalogo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: biblioteca-catalogo
    restart: unless-stopped

    ports:
      - "9502:9502" # Porta pública do microsserviço de Catálogo

    environment:
      PORT: 9502
      NODE_ENV: production
      # # Banco de dados (Configure no .env do servidor)
      # DATABASE_URL: ${DATABASE_URL}
      # # RabbitMQ (servidor externo da faculdade)
      # RABBITMQ_URL: ${RABBITMQ_URL}
      RABBITMQ_RECONNECT_DELAY: 5000
      INFISICAL_CLIENT_ID: "28c50a6c-c408-4185-b846-2f3213d56035"
      INFISICAL_CLIENT_SECRET: "427e0e366c7e0967c2fa6202feffe5894a4ae2d0d4ea9bea0872dd73e07f33ac"
      INFISICAL_PROJECT_ID: "7bd12571-769c-482c-81c7-c13a99bbce76"


    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"